/**
 * Valid product category options for PlasBusinessProductsOrSerive.
 * Used in Add/Edit Product form, API validation, and store navigation.
 * Categories help users browse and filter products in a store.
 */
export const PRODUCT_CATEGORIES = [
  // Food & Grocery
  "Markets",
  "Bakery",
  "Vegetables",
  "Fruits",
  "Meat & Seafood",
  "Drinks",
  "Snacks",
  "Food & Beverage",
  "Dairy & Eggs",
  "Bread & Cereals",
  "Canned & Preserved",
  "Condiments & Sauces",
  "Spices & Seasonings",
  "Frozen Foods",
  "Organic Produce",
  "Grains & Pasta",
  "Oils & Vinegar",
  "Breakfast Foods",
  "Confectionery & Sweets",
  "Beverages & Juices",
  "Water & Soft Drinks",
  "Coffee & Tea",
  "Alcohol & Spirits",
  "Energy Drinks",
  "Plant-Based & Vegan",
  "Gluten-Free",
  "Nuts & Dried Fruits",
  "Ready Meals",
  "Soups & Broths",
  "Ice Cream & Desserts",
  "Chocolates",
  "Cookies & Biscuits",
  "Cereal & Muesli",
  "Honey & Spreads",
  "Seafood",
  "Poultry",
  // Tech & Electronics
  "iPhones",
  "Samsung",
  "Tech & Electronics",
  "Computers & Accessories",
  "Smartphones",
  "Tablets",
  "Laptops",
  "Headphones & Audio",
  "Chargers & Cables",
  "Phone Cases & Accessories",
  "Smartwatches & Wearables",
  "Cameras & Photography",
  "Gaming Consoles",
  "TV & Home Entertainment",
  "Power Banks",
  "Speakers",
  "Smart Home Devices",
  "Earbuds",
  "Screen Protectors",
  "USB Hubs & Adapters",
  "Laptop Bags",
  "Webcams",
  "Keyboards & Mice",
  "External Drives",
  // Fashion & Apparel
  "Gents",
  "Ladies",
  "Babies & Kids",
  "Men's Clothing",
  "Women's Clothing",
  "Kids' Clothing",
  "Shoes & Footwear",
  "Bags & Backpacks",
  "Jewelry & Watches",
  "Accessories",
  "Sportswear",
  "Underwear & Socks",
  "Hats & Caps",
  "Belts & Wallets",
  "Sunglasses",
  "Formal Wear",
  "Casual Wear",
  "Swimwear",
  "Winter Wear",
  "T-Shirts & Tops",
  "Jeans & Pants",
  "Dresses & Skirts",
  "Jackets & Coats",
  "Scarves & Gloves",
  "Formal Shoes",
  "Sneakers",
  "Sandals & Flip-Flops",
  "Handbags",
  "Luggage & Travel",
  // Personal Care & Beauty
  "Hygiene",
  "Care & Beauty",
  "Skincare",
  "Haircare",
  "Makeup & Cosmetics",
  "Perfumes & Fragrances",
  "Soaps & Body Wash",
  "Deodorants",
  "Toothpaste & Oral Care",
  "Shaving & Grooming",
  "Sanitary Products",
  "Baby Care",
  "First Aid & Medical",
  "Nail Care",
  "Face Masks",
  "Sunscreen",
  "Hand Sanitizers",
  "Cotton & Swabs",
  "Hair Tools",
  "Body Lotion",
  "Eye Care",
  "Men's Grooming",
  "Women's Fragrances",
  "Men's Fragrances",
  // Home & Household
  "Pet Food",
  "Office Supplies",
  "Cleaning Supplies",
  "Kitchen & Dining",
  "Bedding & Linens",
  "Bathroom Supplies",
  "Furniture",
  "Decor & Home Accessories",
  "Lighting",
  "Storage & Organization",
  "Laundry & Detergent",
  "Trash Bags & Disposables",
  "Pest Control",
  "Air Fresheners",
  "Cookware & Bakeware",
  "Cutlery",
  "Glassware",
  "Towels",
  "Curtains",
  "Rugs & Carpets",
  "Cushions & Pillows",
  "Plants & Flowers",
  "Clothes Hangers",
  "Ironing",
  "Dishwashing",
  "Mops & Brooms",
  "Batteries",
  "Light Bulbs",
  // Baby & Kids
  "Baby Formula & Food",
  "Diapers & Wipes",
  "Baby Clothes",
  "Toys & Games",
  "School Supplies",
  "Books & Stationery",
  "Baby Gear",
  "Strollers",
  "Cribs & Cots",
  "Baby Bottles",
  "Educational Toys",
  "Board Games",
  "Puzzles",
  "Art & Craft Kits",
  "Lunch Boxes",
  "Backpacks",
  "Coloring Books",
  "Kids' Shoes",
  "Kids' Accessories",
  // Health & Wellness
  "Vitamins & Supplements",
  "Protein & Fitness",
  "Herbal & Natural Remedies",
  "Weight Management",
  "Health Monitors",
  "Pain Relief",
  "Digestive Health",
  "Sleep Aids",
  "Eye Care Products",
  "Ear Care",
  "Blood Pressure Monitors",
  "Thermometers",
  "Masks & PPE",
  // Automotive
  "Car Accessories",
  "Motor Oils & Fluids",
  "Car Care",
  "Tires",
  "Car Freshners",
  "Car Covers",
  "Dash Cams",
  // Sports & Outdoors
  "Sports Equipment",
  "Outdoor Gear",
  "Fitness Accessories",
  "Camping",
  "Bicycles",
  "Yoga & Meditation",
  "Running Gear",
  "Gym Equipment",
  "Fishing",
  "Hiking Boots",
  "Water Bottles",
  "Coolers",
  // Stationery & Art
  "Pens & Pencils",
  "Notebooks & Paper",
  "Art Supplies",
  "Office Furniture",
  "Printers & Ink",
  "Folders & Files",
  "Staplers & Clips",
  "Tape & Glue",
  "Calculators",
  "Whiteboards",
  "Envelopes",
  "Labels",
  "Scissors",
  "Highlighters",
  // Garden & DIY
  "Garden Supplies",
  "Tools & Hardware",
  "Paint & Decorating",
  "Electrical Supplies",
  "Seeds & Fertilizers",
  "Plant Pots",
  "Garden Tools",
  "Outdoor Lighting",
  "Ladders",
  "Safety Equipment",
  "Adhesives",
  "Screws & Nails",
  // Pet Supplies
  "Dog Food",
  "Cat Food",
  "Pet Treats",
  "Pet Toys",
  "Pet Beds",
  "Pet Grooming",
  "Aquarium Supplies",
  "Bird Food",
  // Books & Media
  "Books",
  "Magazines",
  "Music",
  "Movies",
  "Educational Materials",
  // Other
  "Gift Cards",
  "Gifts & Novelty",
  "Religious Items",
  "Party Supplies",
  "Candles",
  "Clocks",
  "Mirrors",
  "Photo Frames",
  "Vases",
  "Reusable Bags",
  "Solar Products",
  "Generators",
  "Sewing & Craft",
  "Musical Instruments",
  "Collectibles",
  "Other",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

/** Grouped categories for dropdown navigation */
export const PRODUCT_CATEGORIES_GROUPED: { group: string; categories: readonly string[] }[] = [
  { group: "Food & Grocery", categories: ["Markets", "Bakery", "Vegetables", "Fruits", "Meat & Seafood", "Drinks", "Snacks", "Food & Beverage", "Dairy & Eggs", "Bread & Cereals", "Canned & Preserved", "Condiments & Sauces", "Spices & Seasonings", "Frozen Foods", "Organic Produce", "Grains & Pasta", "Oils & Vinegar", "Breakfast Foods", "Confectionery & Sweets", "Beverages & Juices", "Water & Soft Drinks", "Coffee & Tea", "Alcohol & Spirits", "Energy Drinks", "Plant-Based & Vegan", "Gluten-Free", "Nuts & Dried Fruits", "Ready Meals", "Soups & Broths", "Ice Cream & Desserts", "Chocolates", "Cookies & Biscuits", "Cereal & Muesli", "Honey & Spreads", "Seafood", "Poultry"] },
  { group: "Tech & Electronics", categories: ["iPhones", "Samsung", "Tech & Electronics", "Computers & Accessories", "Smartphones", "Tablets", "Laptops", "Headphones & Audio", "Chargers & Cables", "Phone Cases & Accessories", "Smartwatches & Wearables", "Cameras & Photography", "Gaming Consoles", "TV & Home Entertainment", "Power Banks", "Speakers", "Smart Home Devices", "Earbuds", "Screen Protectors", "USB Hubs & Adapters", "Laptop Bags", "Webcams", "Keyboards & Mice", "External Drives"] },
  { group: "Fashion & Apparel", categories: ["Gents", "Ladies", "Babies & Kids", "Men's Clothing", "Women's Clothing", "Kids' Clothing", "Shoes & Footwear", "Bags & Backpacks", "Jewelry & Watches", "Accessories", "Sportswear", "Underwear & Socks", "Hats & Caps", "Belts & Wallets", "Sunglasses", "Formal Wear", "Casual Wear", "Swimwear", "Winter Wear", "T-Shirts & Tops", "Jeans & Pants", "Dresses & Skirts", "Jackets & Coats", "Scarves & Gloves", "Formal Shoes", "Sneakers", "Sandals & Flip-Flops", "Handbags", "Luggage & Travel"] },
  { group: "Personal Care & Beauty", categories: ["Hygiene", "Care & Beauty", "Skincare", "Haircare", "Makeup & Cosmetics", "Perfumes & Fragrances", "Soaps & Body Wash", "Deodorants", "Toothpaste & Oral Care", "Shaving & Grooming", "Sanitary Products", "Baby Care", "First Aid & Medical", "Nail Care", "Face Masks", "Sunscreen", "Hand Sanitizers", "Cotton & Swabs", "Hair Tools", "Body Lotion", "Eye Care", "Men's Grooming", "Women's Fragrances", "Men's Fragrances"] },
  { group: "Home & Household", categories: ["Pet Food", "Office Supplies", "Cleaning Supplies", "Kitchen & Dining", "Bedding & Linens", "Bathroom Supplies", "Furniture", "Decor & Home Accessories", "Lighting", "Storage & Organization", "Laundry & Detergent", "Trash Bags & Disposables", "Pest Control", "Air Fresheners", "Cookware & Bakeware", "Cutlery", "Glassware", "Towels", "Curtains", "Rugs & Carpets", "Cushions & Pillows", "Plants & Flowers", "Clothes Hangers", "Ironing", "Dishwashing", "Mops & Brooms", "Batteries", "Light Bulbs"] },
  { group: "Baby & Kids", categories: ["Baby Formula & Food", "Diapers & Wipes", "Baby Clothes", "Toys & Games", "School Supplies", "Books & Stationery", "Baby Gear", "Strollers", "Cribs & Cots", "Baby Bottles", "Educational Toys", "Board Games", "Puzzles", "Art & Craft Kits", "Lunch Boxes", "Backpacks", "Coloring Books", "Kids' Shoes", "Kids' Accessories"] },
  { group: "Health & Wellness", categories: ["Vitamins & Supplements", "Protein & Fitness", "Herbal & Natural Remedies", "Weight Management", "Health Monitors", "Pain Relief", "Digestive Health", "Sleep Aids", "Eye Care Products", "Ear Care", "Blood Pressure Monitors", "Thermometers", "Masks & PPE"] },
  { group: "Automotive", categories: ["Car Accessories", "Motor Oils & Fluids", "Car Care", "Tires", "Car Freshners", "Car Covers", "Dash Cams"] },
  { group: "Sports & Outdoors", categories: ["Sports Equipment", "Outdoor Gear", "Fitness Accessories", "Camping", "Bicycles", "Yoga & Meditation", "Running Gear", "Gym Equipment", "Fishing", "Hiking Boots", "Water Bottles", "Coolers"] },
  { group: "Stationery & Art", categories: ["Pens & Pencils", "Notebooks & Paper", "Art Supplies", "Office Furniture", "Printers & Ink", "Folders & Files", "Staplers & Clips", "Tape & Glue", "Calculators", "Whiteboards", "Envelopes", "Labels", "Scissors", "Highlighters"] },
  { group: "Garden & DIY", categories: ["Garden Supplies", "Tools & Hardware", "Paint & Decorating", "Electrical Supplies", "Seeds & Fertilizers", "Plant Pots", "Garden Tools", "Outdoor Lighting", "Ladders", "Safety Equipment", "Adhesives", "Screws & Nails"] },
  { group: "Pet Supplies", categories: ["Dog Food", "Cat Food", "Pet Treats", "Pet Toys", "Pet Beds", "Pet Grooming", "Aquarium Supplies", "Bird Food"] },
  { group: "Books & Media", categories: ["Books", "Magazines", "Music", "Movies", "Educational Materials"] },
  { group: "Other", categories: ["Gift Cards", "Gifts & Novelty", "Religious Items", "Party Supplies", "Candles", "Clocks", "Mirrors", "Photo Frames", "Vases", "Reusable Bags", "Solar Products", "Generators", "Sewing & Craft", "Musical Instruments", "Collectibles", "Other"] },
];
